---
name: CI/CD

on:
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run all

    # publish on success
    - name: Update latest tag when pushing to main
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        git tag -f latest
        git push -f origin latest
    - name: Publish myself
      uses: cb80/pubrel@latest
      with:
        replace: latest
